<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-GORURFBI" ignored="0" name="Test2" tests="3" failures="1" timestamp="23 Mar 2021 07:22:36 GMT" time="0.055" errors="0">
  <testcase name="tc4" time="0.013" classname="org.login.tester.B1"/>
  <testcase name="tc5" time="0.006" classname="org.login.tester.B1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.login.tester.B1.tc5(B1.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- tc5 -->
  <testcase name="tc6" time="0.001" classname="org.login.tester.B1"/>
</testsuite> <!-- Test2 -->
